nodeLinker: node-modules
packageExtensions:
  "react-scripts@5.0.1":
    peerDependencies:
      typescript: ">=4.8.4 <6"
  "eslint-config-react-app@7.0.1":
    peerDependencies:
      typescript: ">=4.8.4 <6"
