name: Release Linux

on:
  push:
    tags:
      - v*

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  build-linux:
    name: Build Linux binaries
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
      REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
      REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
      REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
      REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
      REACT_APP_MONTHLY_SUBSCRIPTION_PRICE_ID: ${{ secrets.REACT_APP_MONTHLY_SUBSCRIPTION_PRICE_ID }}
      REACT_APP_YEARLY_SUBSCRIPTION_PRICE_ID: ${{ secrets.REACT_APP_YEARLY_SUBSCRIPTION_PRICE_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo snap install snapcraft --classic

      - name: Build and package application
        run: |
          yarn
          yarn build:linux

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.yml,dist/*.AppImage,dist/*.deb,dist/*.rpm 
          draft: true
          token: ${{ secrets.GH_TOKEN }}
